import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    sqlite: 'src/sqlite.ts',
    'client/index': 'src/client/index.ts',
    'adapters/postgres': 'src/adapters/postgres.ts',
    'adapters/mongodb': 'src/adapters/mongodb.ts',
    'adapters/mysql': 'src/adapters/mysql.ts',
    'adapters/redis': 'src/adapters/redis.ts',
    'adapters/dynamodb': 'src/adapters/dynamodb.ts',
    'adapters/elasticsearch': 'src/adapters/elasticsearch.ts',
    'adapters/opensearch': 'src/adapters/opensearch.ts',
    'adapters/snowflake': 'src/adapters/snowflake.ts',
    'adapters/cassandra': 'src/adapters/cassandra.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  platform: 'node',
  external: [
    'node:sqlite',
    'sqlite',
    'node:fs',
    'node:path',
    'pg',
    'mongodb',
    'mysql2',
    'ioredis',
    '@aws-sdk/client-dynamodb',
    '@elastic/elasticsearch',
    '@opensearch-project/opensearch',
    'snowflake-sdk',
    'cassandra-driver',
  ],
})
